name: example
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ^3.4.0
  flutter: ^3.22.3

dependencies:
  flutter:
    sdk: flutter

  custom_navigator:
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
