name: custom_navigator
description: A flutter package that makes it easy to create your own navigator anywhere in the widget tree.
version: 0.3.4
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

